# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.21)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Vanetza::access Vanetza::asn1_support Vanetza::asn1_its Vanetza::asn1_its_r2 Vanetza::asn1_security Vanetza::asn1 Vanetza::btp Vanetza::common Vanetza::dcc Vanetza::facilities Vanetza::geonet Vanetza::gnss Vanetza::net Vanetza::security Vanetza::vanetza)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Vanetza::access
add_library(Vanetza::access SHARED IMPORTED)

set_target_properties(Vanetza::access PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Vanetza::net"
)

# Create imported target Vanetza::asn1_support
add_library(Vanetza::asn1_support SHARED IMPORTED)

set_target_properties(Vanetza::asn1_support PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build;C:/Users/Karel Hevessy/src/vanetza-build/vanetza/asn1/support"
)

# Create imported target Vanetza::asn1_its
add_library(Vanetza::asn1_its SHARED IMPORTED)

set_target_properties(Vanetza::asn1_its PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Vanetza::asn1_support"
)

# Create imported target Vanetza::asn1_its_r2
add_library(Vanetza::asn1_its_r2 SHARED IMPORTED)

set_target_properties(Vanetza::asn1_its_r2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Vanetza::asn1_support"
)

# Create imported target Vanetza::asn1_security
add_library(Vanetza::asn1_security SHARED IMPORTED)

set_target_properties(Vanetza::asn1_security PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Vanetza::asn1_support"
)

# Create imported target Vanetza::asn1
add_library(Vanetza::asn1 SHARED IMPORTED)

set_target_properties(Vanetza::asn1 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Vanetza::asn1_its;Boost::boost"
)

# Create imported target Vanetza::btp
add_library(Vanetza::btp SHARED IMPORTED)

set_target_properties(Vanetza::btp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Boost::boost;Vanetza::geonet"
)

# Create imported target Vanetza::common
add_library(Vanetza::common SHARED IMPORTED)

set_target_properties(Vanetza::common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Boost::date_time;Threads::Threads"
)

# Create imported target Vanetza::dcc
add_library(Vanetza::dcc SHARED IMPORTED)

set_target_properties(Vanetza::dcc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Vanetza::access;Vanetza::net"
)

# Create imported target Vanetza::facilities
add_library(Vanetza::facilities SHARED IMPORTED)

set_target_properties(Vanetza::facilities PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Boost::date_time;Vanetza::asn1;Vanetza::security"
)

# Create imported target Vanetza::geonet
add_library(Vanetza::geonet SHARED IMPORTED)

set_target_properties(Vanetza::geonet PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Boost::date_time;Vanetza::dcc;Vanetza::net;Vanetza::security"
)

# Create imported target Vanetza::gnss
add_library(Vanetza::gnss SHARED IMPORTED)

set_target_properties(Vanetza::gnss PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Boost::date_time"
)

# Create imported target Vanetza::net
add_library(Vanetza::net SHARED IMPORTED)

set_target_properties(Vanetza::net PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Vanetza::common"
)

# Create imported target Vanetza::security
add_library(Vanetza::security SHARED IMPORTED)

set_target_properties(Vanetza::security PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "VANETZA_WITH_CRYPTOPP"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Karel Hevessy/src/vanetza-build"
  INTERFACE_LINK_LIBRARIES "Vanetza::asn1;Vanetza::asn1_security;Vanetza::common;Vanetza::net;CryptoPP::CryptoPP"
)

# Create imported target Vanetza::vanetza
add_library(Vanetza::vanetza INTERFACE IMPORTED)

set_target_properties(Vanetza::vanetza PROPERTIES
  INTERFACE_LINK_LIBRARIES "Vanetza::access;Vanetza::asn1_support;Vanetza::asn1_its;Vanetza::asn1_its_r2;Vanetza::asn1_security;Vanetza::asn1;Vanetza::btp;Vanetza::common;Vanetza::dcc;Vanetza::facilities;Vanetza::geonet;Vanetza::gnss;Vanetza::net;Vanetza::security"
)

# Import target "Vanetza::access" for configuration "Debug"
set_property(TARGET Vanetza::access APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::access PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_access.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_access.dll"
  )

# Import target "Vanetza::asn1_support" for configuration "Debug"
set_property(TARGET Vanetza::asn1_support APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::asn1_support PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_asn1_support.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_asn1_support.dll"
  )

# Import target "Vanetza::asn1_its" for configuration "Debug"
set_property(TARGET Vanetza::asn1_its APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::asn1_its PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_asn1_its.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_asn1_its.dll"
  )

# Import target "Vanetza::asn1_its_r2" for configuration "Debug"
set_property(TARGET Vanetza::asn1_its_r2 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::asn1_its_r2 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_asn1_its_r2.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_asn1_its_r2.dll"
  )

# Import target "Vanetza::asn1_security" for configuration "Debug"
set_property(TARGET Vanetza::asn1_security APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::asn1_security PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_asn1_security.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_asn1_security.dll"
  )

# Import target "Vanetza::asn1" for configuration "Debug"
set_property(TARGET Vanetza::asn1 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::asn1 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_asn1.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_asn1.dll"
  )

# Import target "Vanetza::btp" for configuration "Debug"
set_property(TARGET Vanetza::btp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::btp PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_btp.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_btp.dll"
  )

# Import target "Vanetza::common" for configuration "Debug"
set_property(TARGET Vanetza::common APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::common PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_common.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_common.dll"
  )

# Import target "Vanetza::dcc" for configuration "Debug"
set_property(TARGET Vanetza::dcc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::dcc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_dcc.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_dcc.dll"
  )

# Import target "Vanetza::facilities" for configuration "Debug"
set_property(TARGET Vanetza::facilities APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::facilities PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_facilities.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "Vanetza::geonet"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_facilities.dll"
  )

# Import target "Vanetza::geonet" for configuration "Debug"
set_property(TARGET Vanetza::geonet APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::geonet PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_geonet.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_geonet.dll"
  )

# Import target "Vanetza::gnss" for configuration "Debug"
set_property(TARGET Vanetza::gnss APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::gnss PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_gnss.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_gnss.dll"
  )

# Import target "Vanetza::net" for configuration "Debug"
set_property(TARGET Vanetza::net APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::net PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_net.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_net.dll"
  )

# Import target "Vanetza::security" for configuration "Debug"
set_property(TARGET Vanetza::security APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Vanetza::security PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Debug/vanetza_security.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Debug/vanetza_security.dll"
  )

# Import target "Vanetza::access" for configuration "Release"
set_property(TARGET Vanetza::access APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::access PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_access.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_access.dll"
  )

# Import target "Vanetza::asn1_support" for configuration "Release"
set_property(TARGET Vanetza::asn1_support APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::asn1_support PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_asn1_support.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_asn1_support.dll"
  )

# Import target "Vanetza::asn1_its" for configuration "Release"
set_property(TARGET Vanetza::asn1_its APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::asn1_its PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_asn1_its.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_asn1_its.dll"
  )

# Import target "Vanetza::asn1_its_r2" for configuration "Release"
set_property(TARGET Vanetza::asn1_its_r2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::asn1_its_r2 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_asn1_its_r2.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_asn1_its_r2.dll"
  )

# Import target "Vanetza::asn1_security" for configuration "Release"
set_property(TARGET Vanetza::asn1_security APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::asn1_security PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_asn1_security.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_asn1_security.dll"
  )

# Import target "Vanetza::asn1" for configuration "Release"
set_property(TARGET Vanetza::asn1 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::asn1 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_asn1.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_asn1.dll"
  )

# Import target "Vanetza::btp" for configuration "Release"
set_property(TARGET Vanetza::btp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::btp PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_btp.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_btp.dll"
  )

# Import target "Vanetza::common" for configuration "Release"
set_property(TARGET Vanetza::common APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::common PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_common.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_common.dll"
  )

# Import target "Vanetza::dcc" for configuration "Release"
set_property(TARGET Vanetza::dcc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::dcc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_dcc.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_dcc.dll"
  )

# Import target "Vanetza::facilities" for configuration "Release"
set_property(TARGET Vanetza::facilities APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::facilities PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_facilities.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "Vanetza::geonet"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_facilities.dll"
  )

# Import target "Vanetza::geonet" for configuration "Release"
set_property(TARGET Vanetza::geonet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::geonet PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_geonet.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_geonet.dll"
  )

# Import target "Vanetza::gnss" for configuration "Release"
set_property(TARGET Vanetza::gnss APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::gnss PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_gnss.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_gnss.dll"
  )

# Import target "Vanetza::net" for configuration "Release"
set_property(TARGET Vanetza::net APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::net PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_net.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_net.dll"
  )

# Import target "Vanetza::security" for configuration "Release"
set_property(TARGET Vanetza::security APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Vanetza::security PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/Release/vanetza_security.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/Release/vanetza_security.dll"
  )

# Import target "Vanetza::access" for configuration "MinSizeRel"
set_property(TARGET Vanetza::access APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::access PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_access.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_access.dll"
  )

# Import target "Vanetza::asn1_support" for configuration "MinSizeRel"
set_property(TARGET Vanetza::asn1_support APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::asn1_support PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_asn1_support.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_asn1_support.dll"
  )

# Import target "Vanetza::asn1_its" for configuration "MinSizeRel"
set_property(TARGET Vanetza::asn1_its APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::asn1_its PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_asn1_its.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_asn1_its.dll"
  )

# Import target "Vanetza::asn1_its_r2" for configuration "MinSizeRel"
set_property(TARGET Vanetza::asn1_its_r2 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::asn1_its_r2 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_asn1_its_r2.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_asn1_its_r2.dll"
  )

# Import target "Vanetza::asn1_security" for configuration "MinSizeRel"
set_property(TARGET Vanetza::asn1_security APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::asn1_security PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_asn1_security.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_asn1_security.dll"
  )

# Import target "Vanetza::asn1" for configuration "MinSizeRel"
set_property(TARGET Vanetza::asn1 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::asn1 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_asn1.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_asn1.dll"
  )

# Import target "Vanetza::btp" for configuration "MinSizeRel"
set_property(TARGET Vanetza::btp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::btp PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_btp.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_btp.dll"
  )

# Import target "Vanetza::common" for configuration "MinSizeRel"
set_property(TARGET Vanetza::common APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::common PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_common.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_common.dll"
  )

# Import target "Vanetza::dcc" for configuration "MinSizeRel"
set_property(TARGET Vanetza::dcc APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::dcc PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_dcc.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_dcc.dll"
  )

# Import target "Vanetza::facilities" for configuration "MinSizeRel"
set_property(TARGET Vanetza::facilities APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::facilities PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_facilities.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "Vanetza::geonet"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_facilities.dll"
  )

# Import target "Vanetza::geonet" for configuration "MinSizeRel"
set_property(TARGET Vanetza::geonet APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::geonet PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_geonet.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_geonet.dll"
  )

# Import target "Vanetza::gnss" for configuration "MinSizeRel"
set_property(TARGET Vanetza::gnss APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::gnss PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_gnss.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_gnss.dll"
  )

# Import target "Vanetza::net" for configuration "MinSizeRel"
set_property(TARGET Vanetza::net APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::net PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_net.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_net.dll"
  )

# Import target "Vanetza::security" for configuration "MinSizeRel"
set_property(TARGET Vanetza::security APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Vanetza::security PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/MinSizeRel/vanetza_security.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/MinSizeRel/vanetza_security.dll"
  )

# Import target "Vanetza::access" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::access APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::access PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_access.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_access.dll"
  )

# Import target "Vanetza::asn1_support" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::asn1_support APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::asn1_support PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_asn1_support.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_asn1_support.dll"
  )

# Import target "Vanetza::asn1_its" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::asn1_its APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::asn1_its PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_asn1_its.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_asn1_its.dll"
  )

# Import target "Vanetza::asn1_its_r2" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::asn1_its_r2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::asn1_its_r2 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_asn1_its_r2.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_asn1_its_r2.dll"
  )

# Import target "Vanetza::asn1_security" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::asn1_security APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::asn1_security PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_asn1_security.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_asn1_security.dll"
  )

# Import target "Vanetza::asn1" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::asn1 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::asn1 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_asn1.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_asn1.dll"
  )

# Import target "Vanetza::btp" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::btp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::btp PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_btp.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_btp.dll"
  )

# Import target "Vanetza::common" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::common APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::common PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_common.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_common.dll"
  )

# Import target "Vanetza::dcc" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::dcc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::dcc PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_dcc.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_dcc.dll"
  )

# Import target "Vanetza::facilities" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::facilities APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::facilities PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_facilities.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "Vanetza::geonet"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_facilities.dll"
  )

# Import target "Vanetza::geonet" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::geonet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::geonet PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_geonet.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_geonet.dll"
  )

# Import target "Vanetza::gnss" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::gnss APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::gnss PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_gnss.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_gnss.dll"
  )

# Import target "Vanetza::net" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::net APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::net PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_net.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_net.dll"
  )

# Import target "Vanetza::security" for configuration "RelWithDebInfo"
set_property(TARGET Vanetza::security APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Vanetza::security PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/lib/static/RelWithDebInfo/vanetza_security.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Karel Hevessy/src/vanetza-build/shared/bin/RelWithDebInfo/vanetza_security.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
